# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6153cfa4fc4694bceb1c5247ca78448a9abca5bc7392e23a03c3cab4745dfff0ad032fe4fa1975d02c50045b00c3ca90b29d5031e0d7f587307139a812f2df2

test:
  secret_key_base: f292bc10f1d3e1e7ed02c02e0231f61386f5951f1ce75436dbdf8c273e8f2d2781b31ef6c52114d45943ec18d59a14e63464c111bf57fd4ff8be6951d3f9b2de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
